### ISSUE TITLE
Error in loading certain filters

### ISSUE THREAD

**Issue by jaladh-singhal** [starkit/wsynphot#13]
There are some filters which throw error when passed to `wsynphot.FilterCurve.load_filter()`. Those which I have identified are: 
1. `Scorpio/Comet/CO+`
```bash
IndexError                                Traceback (most recent call last)
<ipython-input-12-d7dbfca1863b> in <module>()
      1 plt.figure()
----> 2 filter = wsynphot.FilterCurve.load_filter('Scorpio/Comet/CO+')
      3 filter.plot(gca())

/home/jpolygon/miniconda3/envs/wsp-doc-new/lib/python2.7/site-packages/wsynphot-0.0.dev71-py2.7.egg/wsynphot/base.pyc in load_filter(cls, filter_name, interpolation_kind)
    136             wavelength_unit = 'angstrom'
    137 
--> 138             wavelength = filter.wavelength.values * u.Unit(wavelength_unit)
    139 
    140             return cls(wavelength, filter.transmission_lambda.values,

/home/jpolygon/miniconda3/envs/wsp-doc-new/lib/python2.7/site-packages/astropy/units/core.pyc in __rmul__(self, m)
    724                 return result
    725             else:
--> 726                 return Quantity(m, self)
    727         except TypeError:
    728             return NotImplemented

/home/jpolygon/miniconda3/envs/wsp-doc-new/lib/python2.7/site-packages/astropy/units/quantity.pyc in __new__(cls, value, unit, dtype, copy, order, subok, ndmin)
    377         if (value.dtype.kind in 'OSU' and
    378             not (value.dtype.kind == 'O' and
--> 379                  isinstance(value.item(() if value.ndim == 0 else 0),
    380                             numbers.Number))):
    381             raise TypeError("The value must be a valid Python or "

IndexError: index 0 is out of bounds for axis 0 with size 0
```
2. All 4 filters under `WISE/WISE`
```bash
TypeError                                 Traceback (most recent call last)
<ipython-input-13-f9b35bab0fdd> in <module>()
      1 plt.figure()
----> 2 filter = wsynphot.FilterCurve.load_filter('WISE/WISE/W1')
      3 filter.plot(gca())

/home/jpolygon/miniconda3/envs/wsp-doc-new/lib/python2.7/site-packages/wsynphot-0.0.dev71-py2.7.egg/wsynphot/base.pyc in load_filter(cls, filter_name, interpolation_kind)
    136             wavelength_unit = 'angstrom'
    137 
--> 138             wavelength = filter.wavelength.values * u.Unit(wavelength_unit)
    139 
    140             return cls(wavelength, filter.transmission_lambda.values,

TypeError: unsupported operand type(s) for *: 'numpy.ndarray' and 'Unit'
```
There may be also a few other filters which throw error on loading (can be identified by writing a automated testing script).

**Comment by jaladh-singhal** [comment]
@followthesheep @wkerzendorf I wrote some code to identify all the erroneous filters present in dataset `filter_data.h5` (out of 4409 filters). Then I obtained [`filter_store`](https://github.com/starkit/wsynphot/blob/7559ac5d3e1950ddbd31939ec11d1a235fd5806e/wsynphot/base.py#L126) and observed [filter dataframe](https://github.com/starkit/wsynphot/blob/7559ac5d3e1950ddbd31939ec11d1a235fd5806e/wsynphot/base.py#L128) containing values of `wavelength` and `transmission_lambda` for each erroneous filter. Hence I identified the cause of error for each of them:

S.N. | Obsv.Facility/Instrument | Filter Name | No. of Filters | Error Cause
--- | --- | --- | --- | ---
1 | CTIO/MosaicII | Halpha+80 | 1 | 0 rows (Empty df)
2 | HST/WFPC2 | All | 41 | Garbage strings (in both col)
3 | INT/IPHAS | All | 3 | Garbage strings (in col transmission)
4 | KPNO/Mosaic | Halpha+<no.> | 4 | 0 rows (Empty df)
5 | Scorpio/Comet | CO+ | 1 | 0 rows (Empty df)
6 | WISE/WISE | All | 4 | Garbage strings (in both col)
  | . | . | .| Total = 54 |
 
Clearly, there are 2 problems which can be solved as follows:
1. Due to garbage strings the `dtype` of numpy array comes out to be `object` instead of required `float64` -> Basic Data cleaning is required which drops string-containing rows from the dataframe, which can be easily done by writing only a few lines of code. 
2. The empty dataframes -> They can be eliminated once pandas read the data from HDF5 file by explicitly removing such filters (totaling to 6 only). It requires (i)to drop those 6 rows from [`filter_index`](https://github.com/starkit/wsynphot/blob/7559ac5d3e1950ddbd31939ec11d1a235fd5806e/wsynphot/base.py#L71) so that they are not listed before user, and (ii)to delete those 6 dataframes (or tables) from [`filter_store`](https://github.com/starkit/wsynphot/blob/7559ac5d3e1950ddbd31939ec11d1a235fd5806e/wsynphot/base.py#L126) so that if they will be accessed, [`ValueError`](https://github.com/starkit/wsynphot/blob/7559ac5d3e1950ddbd31939ec11d1a235fd5806e/wsynphot/base.py#L131) will be raised.

Also there's possibility that instead of eliminating data, we could better use a more accurate dataset, a new HDF5 file. But if removing those 6 filters doesn't cost much loss to us, then could I start resolving errors by the approach shared above? 
Please tell me your decision, I'll do accordingly.

**Comment by jaladh-singhal** [comment]
As I investigated the code in `wsynphot/data` that had generated the hdf file of filters dataset used by wsynphot (i.e. present at Zenodo). I found that there's no problem with our code that could have introduced the above mentioned errors. The problem lies in dataset (wavelength, transmission values) of mentioned filters at SVO i.e. being fetched as it is by our code. The above listed problems can be classified as:
1. **Garbage strings:** At SVO, filters with this problem (S.N. 2,3,6 in above table) are able to show filter curves, but if we look at their data file, the garbage strings can be clearly found in it. For instance: Data file http://svo2.cab.inta-csic.es/svo/theory/fps/getdata.php?format=ascii&id=HST/WFPC2.f218w provided by SVO for filter [`HST/WFPC2.f218w`](http://svo2.cab.inta-csic.es/svo/theory/fps/index.php?id=HST/WFPC2.f218w&&mode=browse&gname=HST&gname2=WFPC2#filter). Possibly, their code at backend is cleaning data before plotting filter curve, but ours is failing because we're taking it in Pandas dataframe as it is. So I can resolve this by writing few lines of code to clean data before using it.
2. **Empty dataset:** At SVO, when we click on filters with this problem (S.N. 1,4,5 above), filter curve doesn't appear (though it is still a mystery to me, how it is appearing in grouped filter curves). For instance: try clicking on filter `CO+` at http://svo2.cab.inta-csic.es/theory/fps/index.php?&mode=browse&gname=Scorpio&gname2=Comet. Thereby filter dataset fetched corresponding to such filters is empty (0 rows) like it can be seen in [fetched dataset of CO+](https://github.com/starkit/wsynphot/blob/master/wsynphot/data/SVO/Scorpio/Comet.CO+). So we have two solutions:
   1. Contact SVO Filter Profile Service and report them about such empty datasets. The only contact I was able to find is an email address: svo-support@cab.inta-csic.es
   2. Delete them from our dataset as they are only 6 in number and since they're not even present at SVO, so it shouldn't be count as any loss of data.

**Comment by followthesheep** [comment]
Nice work checking on this. I think we should try to filter out bad strings in the filter curves when we process them. When I download HST_WFPC2.f218w.dat from your link, I don't see bad strings in that file, but maybe it's because I'm just viewing them in a text editor. 

For now, we can remove the filters with no data, but it would be good to contact the SVO support email to point them to the filters with no data so they will know. If there are filters with bad strings, it would also be good to report it to them.

**Comment by jaladh-singhal** [comment]
> When I download HST_WFPC2.f218w.dat from your link, I don't see bad strings in that file, but maybe it's because I'm just viewing them in a text editor.

I don't understand why that might have happened with you. This is how it appears in my editor:
![img](https://drive.google.com/uc?id=13eTQSpUUfM9nBSluswaiHvY33EDXxQhm)
i.e. same as [data file in `wsynphot/data`](https://github.com/starkit/wsynphot/blob/master/wsynphot/data/SVO/HST/WFPC2.f218w) from which hdf file might had been created.

This creates problem when dataframe is retrieved from filter data in hdf file by the code in `load_filter()` function, as I checked here:
![img](https://drive.google.com/uc?id=1ZVQV7fuDXRTo1XgGsZczOTK8nKLfzlWV)

I've eliminated these bad strings under PR#18

**Comment by followthesheep** [comment]
Oh, I think you just need to add comment="#" to the pandas.read_csv call.
Those # are comment characters, the lines are not garbage text. They hold
information about these particular filters.

**Comment by jaladh-singhal** [comment]
@followthesheep Actually, they're [being directly read from HDF file](https://github.com/starkit/wsynphot/blob/0f9cc961c83cf7dccbf5270ae6faac22f549a2de/wsynphot/base.py#L126) as a dataframe `filter` - and `HDFStore` of pandas doesn't seem to provide such functionality. So I had to remove them from dataframe itself.

**Comment by jaladh-singhal** [comment]
> For now, we can remove the filters with no data

@followthesheep OK, I can add a code like this:
```python
if filter.empty:
    raise ValueError('Data for <filter-name> is not available`)
```
after [the line in which filter dataframe is created](https://github.com/starkit/wsynphot/blob/0f9cc961c83cf7dccbf5270ae6faac22f549a2de/wsynphot/base.py#L128) to prevent further flow of execution. Will that be fine?

And another concern is that, these filters with empty dataset also appear in [index part of HDF file](https://github.com/starkit/wsynphot/blob/0f9cc961c83cf7dccbf5270ae6faac22f549a2de/wsynphot/base.py#L71). So to prevent them appearing before user when user access the list of filters using `list_filters()`, I think I should eliminate them from appearing in the list (i.e. `filter_index` dataframe) by simply dropping the rows of such 6 filters, as well. What do you suggest?

**Comment by followthesheep** [comment]
I think your solution is good. However, I think we should also recreate the HDF5 file to not include the comment lines. Can you modify the script that creates the HDF5 file do that check?

**Comment by jaladh-singhal** [comment]
@followthesheep Yeah, this I wanted to ask. There is code to create HDF file present in `wsynphot/data` which you guys might have used locally to create HDF file and upload it on Zenodo. So if you're creating a new HDF file again, I could do that. But if not, then the solution I did in PR#18 (data cleaning of filter dataframe) achieves our purpose. So, are you planning to create new HDF file or am I missing something?

**Comment by jaladh-singhal** [comment]
After contacting with SVO Filter Profile Service, they fixed these issues. Also it has led our ingest_from_svo notebook to contain the code which can clean bad strings as well as eliminate filters with empty data file, to resolve any future issues.
